# Generated by Django 4.2.3 on 2023-07-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_exer_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
            ],
        ),
    ]
