# Generated by Django 4.2.3 on 2023-07-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_downloaphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloaPhoto',
        ),
    ]
