# Generated by Django 4.2.3 on 2023-07-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_gymreview_gymplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymplace',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_photo', verbose_name='이미지'),
        ),
    ]
