# Generated by Django 4.2.3 on 2023-07-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_arm_health_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arm_health',
            name='arm_name',
            field=models.CharField(max_length=20),
        ),
    ]
