# Generated by Django 4.2.3 on 2023-07-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_delete_downloaphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=20)),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
