# Generated by Django 4.2.3 on 2023-07-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gymPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeName', models.CharField(max_length=128, verbose_name='이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
    ]
