# Generated by Django 4.2.3 on 2023-07-12 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0002_gymreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymplace',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_gyms', to=settings.AUTH_USER_MODEL),
        ),
    ]
